export const dummyTeamData = [
    {
        id: 1,
        name: "Chennai Super Kings",
        logo: "https://upload.wikimedia.org/wikipedia/en/f/f9/Chennai_Super_Kings.png",
        captain: "MS Dhoni",
        coach: "Stephen Fleming",
        owner: "Chennai Super Kings Cricket Limited",
        venue: "M. A. Chidambaram Stadium",
        trophies: [2010, 2011, 2018, 2021, 2023],
        players:[
            { id: 1, name: "Ruturaj Gaikwad", skill: "Batter", image: "https://example.com/images/ruturaj_gaikwad.jpg" },
            { id: 2, name: "Ravindra Jadeja", skill: "All-Rounder", image: "https://example.com/images/ravindra_jadeja.jpg" },
            { id: 3, name: "Matheesha Pathirana", skill: "Bowler", image: "https://example.com/images/matheesha_pathirana.jpg" },
            { id: 4, name: "Shivam Dube", skill: "All-Rounder", image: "https://example.com/images/shivam_dube.jpg" },
            { id: 5, name: "MS Dhoni", skill: "WK-Batter", image: "https://example.com/images/ms_dhoni.jpg" },
            { id: 6, name: "Devon Conway", skill: "WK-Batter", image: "https://example.com/images/devon_conway.jpg" },
            { id: 7, name: "Rahul Tripathi", skill: "Batter", image: "https://example.com/images/rahul_tripathi.jpg" },
            { id: 8, name: "Rachin Ravindra", skill: "All-Rounder", image: "https://example.com/images/rachin_ravindra.jpg" },
            { id: 9, name: "Ravichandran Ashwin", skill: "All-Rounder", image: "https://example.com/images/ravichandran_ashwin.jpg" },
            { id: 10, name: "Syed Khaleel Ahmed", skill: "Bowler", image: "https://example.com/images/khaleel_ahmed.jpg" },
            { id: 11, name: "Noor Ahmad", skill: "Bowler", image: "https://example.com/images/noor_ahmad.jpg" },
            { id: 12, name: "Vijay Shankar", skill: "All-Rounder", image: "https://example.com/images/vijay_shankar.jpg" },
            { id: 13, name: "Sam Curran", skill: "All-Rounder", image: "https://example.com/images/sam_curran.jpg" },
            { id: 14, name: "Shaik Rasheed", skill: "Batter", image: "https://example.com/images/shaik_rasheed.jpg" },
            { id: 15, name: "Anshul Kamboj", skill: "Bowler", image: "https://example.com/images/anshul_kamboj.jpg" },
            { id: 16, name: "Mukesh Choudhary", skill: "Bowler", image: "https://example.com/images/mukesh_choudhary.jpg" },
            { id: 17, name: "Deepak Hooda", skill: "All-Rounder", image: "https://example.com/images/deepak_hooda.jpg" },
            { id: 18, name: "Gurjapneet Singh", skill: "Bowler", image: "https://example.com/images/gurjapneet_singh.jpg" },
            { id: 19, name: "Nathan Ellis", skill: "Bowler", image: "https://example.com/images/nathan_ellis.jpg" },
            { id: 20, name: "Ramakrishna Ghosh", skill: "Batter", image: "https://example.com/images/ramakrishna_ghosh.jpg" },
            { id: 21, name: "Kamlesh Nagarkoti", skill: "Bowler", image: "https://example.com/images/kamlesh_nagarkoti.jpg" },
            { id: 22, name: "Jamie Overton", skill: "All-Rounder", image: "https://example.com/images/jamie_overton.jpg" },
            { id: 23, name: "Shreyas Gopal", skill: "All-Rounder", image: "https://example.com/images/shreyas_gopal.jpg" },
            { id: 24, name: "Vansh Bedi", skill: "Bowler", image: "https://example.com/images/vansh_bedi.jpg" },
            { id: 25, name: "Andre Siddarth C.", skill: "Bowler", image: "https://example.com/images/andre_siddarth_c.jpg" }
          ]
    }     
]     

export const archieveMenu = [
    {
      teams: [
        {
          team_name: 'Chennai Super Kings',
          seasons: [
            {
              year: 2024,
              position: 5,
              top_scorer: 'Ruturaj Gaikwad',
              top_score: 583,
              most_wickets: 'Tushar Deshpande',
              wicket_count: 17,
            },
            {
              year: 2023,
              position: 2,
              top_scorer: 'Devon Conway',
              top_score: 672,
              most_wickets: 'Tushar Deshpande',
              wicket_count: 21,
            },
            {
              year: 2022,
              position: 9,
              top_scorer: 'Ruturaj Gaikwad',
              top_score: 368,
              most_wickets: 'Dwayne Bravo',
              wicket_count: 16,
            },
            {
              year: 2021,
              position: 1,
              top_scorer: 'Ruturaj Gaikwad',
              top_score: 635,
              most_wickets: 'Shardul Thakur',
              wicket_count: 21,
            },
            {
              year: 2020,
              position: 7,
              top_scorer: 'Faf du Plessis',
              top_score: 449,
              most_wickets: 'Sam Curran',
              wicket_count: 13,
            },
            {
              year: 2019,
              position: 2,
              top_scorer: 'MS Dhoni',
              top_score: 416,
              most_wickets: 'Imran Tahir',
              wicket_count: 26,
            },
            {
              year: 2018,
              position: 1,
              top_scorer: 'Ambati Rayudu',
              top_score: 602,
              most_wickets: 'Shardul Thakur',
              wicket_count: 16,
            },
            {
              year: 2015,
              position: 2,
              top_scorer: 'Brendon McCullum',
              top_score: 436,
              most_wickets: 'Dwayne Bravo',
              wicket_count: 26,
            },
            {
              year: 2014,
              position: 3,
              top_scorer: 'Dwayne Smith',
              top_score: 566,
              most_wickets: 'Mohit Sharma',
              wicket_count: 23,
            },
            {
              year: 2013,
              position: 2,
              top_scorer: 'Michael Hussey',
              top_score: 733,
              most_wickets: 'Dwayne Bravo',
              wicket_count: 32,
            },
            {
              year: 2012,
              position: 2,
              top_scorer: 'Suresh Raina',
              top_score: 441,
              most_wickets: 'Ben Hilfenhaus',
              wicket_count: 14,
            },
            {
              year: 2011,
              position: 1,
              top_scorer: 'Michael Hussey',
              top_score: 492,
              most_wickets: 'Ravichandran Ashwin',
              wicket_count: 20,
            },
            {
              year: 2010,
              position: 1,
              top_scorer: 'Suresh Raina',
              top_score: 520,
              most_wickets: 'Muttiah Muralitharan',
              wicket_count: 15,
            },
            {
              year: 2009,
              position: 4,
              top_scorer: 'Matthew Hayden',
              top_score: 572,
              most_wickets: 'Muttiah Muralitharan',
              wicket_count: 14,
            },
            {
              year: 2008,
              position: 2,
              top_scorer: 'Suresh Raina',
              top_score: 421,
              most_wickets: 'Albie Morkel',
              wicket_count: 17,
            },
          ],
        },
        {
          team_name: 'Delhi Capitals',
          seasons: [
            {
              year: 2024,
              position: 6,
              top_scorer: 'Rishabh Pant',
              top_score: 446,
              most_wickets: 'Khaleel Ahmed',
              wicket_count: 17,
            },
            {
              year: 2023,
              position: 9,
              top_scorer: 'David Warner',
              top_score: 516,
              most_wickets: 'Mitchell Marsh',
              wicket_count: 12,
            },
            {
              year: 2022,
              position: 5,
              top_scorer: 'David Warner',
              top_score: 432,
              most_wickets: 'Kuldeep Yadav',
              wicket_count: 21,
            },
            {
              year: 2021,
              position: 3,
              top_scorer: 'Shikhar Dhawan',
              top_score: 587,
              most_wickets: 'Avesh Khan',
              wicket_count: 24,
            },
            {
              year: 2020,
              position: 2,
              top_scorer: 'Shikhar Dhawan',
              top_score: 618,
              most_wickets: 'Kagiso Rabada',
              wicket_count: 30,
            },
            {
              year: 2019,
              position: 3,
              top_scorer: 'Shikhar Dhawan',
              top_score: 521,
              most_wickets: 'Kagiso Rabada',
              wicket_count: 25,
            },
            {
              year: 2018,
              position: 8,
              top_scorer: 'Rishabh Pant',
              top_score: 684,
              most_wickets: 'Trent Boult',
              wicket_count: 18,
            },
            {
              year: 2017,
              position: 6,
              top_scorer: 'Sanju Samson',
              top_score: 386,
              most_wickets: 'Pat Cummins',
              wicket_count: 15,
            },
            {
              year: 2016,
              position: 6,
              top_scorer: 'Quinton de Kock',
              top_score: 445,
              most_wickets: 'Amit Mishra',
              wicket_count: 13,
            },
            {
              year: 2015,
              position: 7,
              top_scorer: 'Shreyas Iyer',
              top_score: 439,
              most_wickets: 'Nathan Coulter-Nile',
              wicket_count: 15,
            },
            {
              year: 2014,
              position: 8,
              top_scorer: 'JP Duminy',
              top_score: 410,
              most_wickets: 'Imran Tahir',
              wicket_count: 9,
            },
            {
              year: 2013,
              position: 9,
              top_scorer: 'David Warner',
              top_score: 410,
              most_wickets: 'Umesh Yadav',
              wicket_count: 16,
            },
            {
              year: 2012,
              position: 3,
              top_scorer: 'Virender Sehwag',
              top_score: 495,
              most_wickets: 'Morne Morkel',
              wicket_count: 25,
            },
            {
              year: 2011,
              position: 10,
              top_scorer: 'Virender Sehwag',
              top_score: 424,
              most_wickets: 'Morne Morkel',
              wicket_count: 13,
            },
            {
              year: 2010,
              position: 5,
              top_scorer: 'Virender Sehwag',
              top_score: 356,
              most_wickets: 'Amit Mishra',
              wicket_count: 17,
            },
            {
              year: 2009,
              position: 3,
              top_scorer: 'AB de Villiers',
              top_score: 465,
              most_wickets: 'Ashish Nehra',
              wicket_count: 19,
            },
            {
              year: 2008,
              position: 4,
              top_scorer: 'Gautam Gambhir',
              top_score: 534,
              most_wickets: 'Yo Mahesh',
              wicket_count: 16,
            },
          ],
        },
        {
          team_name: 'Gujarat Titans',
          seasons: [
            {
              year: 2024,
              position: 8,
              top_scorer: 'Sai Sudharsan',
              top_score: 527,
              most_wickets: 'Mohit Sharma',
              wicket_count: 13,
            },
            {
              year: 2023,
              position: 1,
              top_scorer: 'Shubman Gill',
              top_score: 890,
              most_wickets: 'Mohammad Shami',
              wicket_count: 28,
            },
            {
              year: 2022,
              position: 1,
              top_scorer: 'Hardik Pandya',
              top_score: 487,
              most_wickets: 'Mohammad Shami',
              wicket_count: 20,
            },
          ],
        },
        {
          team_name: 'Kolkata Knight Riders',
          seasons: [
            {
              year: 2024,
              position: 1,
              top_scorer: 'Sunil Narine',
              top_score: 488,
              most_wickets: 'Varun Chakaravarthy',
              wicket_count: 21,
            },
            {
              year: 2023,
              position: 7,
              top_scorer: 'Rinku Singh',
              top_score: 474,
              most_wickets: 'Varun Chakaravarthy',
              wicket_count: 20,
            },
            {
              year: 2022,
              position: 7,
              top_scorer: 'Shreyas Iyer',
              top_score: 401,
              most_wickets: 'Andre Russell',
              wicket_count: 17,
            },
            {
              year: 2021,
              position: 2,
              top_scorer: 'Shubman Gill',
              top_score: 478,
              most_wickets: 'Varun Chakaravarthy',
              wicket_count: 18,
            },
            {
              year: 2020,
              position: 5,
              top_scorer: 'Shubman Gill',
              top_score: 440,
              most_wickets: 'Varun Chakaravarthy',
              wicket_count: 17,
            },
            {
              year: 2019,
              position: 5,
              top_scorer: 'Andre Russell',
              top_score: 510,
              most_wickets: 'Andre Russell',
              wicket_count: 11,
            },
            {
              year: 2018,
              position: 3,
              top_scorer: 'Dinesh Karthik',
              top_score: 498,
              most_wickets: 'Sunil Narine',
              wicket_count: 17,
            },
            {
              year: 2017,
              position: 3,
              top_scorer: 'Gautam Gambhir',
              top_score: 498,
              most_wickets: 'Chris Woakes',
              wicket_count: 17,
            },
            {
              year: 2016,
              position: 4,
              top_scorer: 'Gautam Gambhir',
              top_score: 501,
              most_wickets: 'Andre Russell',
              wicket_count: 15,
            },
            {
              year: 2015,
              position: 5,
              top_scorer: 'Robin Uthappa',
              top_score: 364,
              most_wickets: 'Andre Russell',
              wicket_count: 14,
            },
            {
              year: 2014,
              position: 1,
              top_scorer: 'Robin Uthappa',
              top_score: 660,
              most_wickets: 'Sunil Narine',
              wicket_count: 21,
            },
            {
              year: 2013,
              position: 7,
              top_scorer: 'Gautam Gambhir',
              top_score: 406,
              most_wickets: 'Sunil Narine',
              wicket_count: 22,
            },
            {
              year: 2012,
              position: 1,
              top_scorer: 'Gautam Gambhir',
              top_score: 590,
              most_wickets: 'Sunil Narine',
              wicket_count: 24,
            },
            {
              year: 2011,
              position: 4,
              top_scorer: 'Jacques Kallis',
              top_score: 424,
              most_wickets: 'Iqbal Abdulla',
              wicket_count: 16,
            },
            {
              year: 2010,
              position: 6,
              top_scorer: 'Sourav Ganguly',
              top_score: 493,
              most_wickets: 'Ashok Dinda',
              wicket_count: 9,
            },
            {
              year: 2009,
              position: 8,
              top_scorer: 'Brad Hodge',
              top_score: 365,
              most_wickets: 'Ishant Sharma',
              wicket_count: 11,
            },
            {
              year: 2008,
              position: 6,
              top_scorer: 'Sourav Ganguly',
              top_score: 349,
              most_wickets: 'Umar Gul',
              wicket_count: 12,
            },
          ],
        },
        {
          team_name: 'Lucknow Super Giants',
          seasons: [
            {
              year: 2024,
              position: 7,
              top_scorer: 'K L Rahul',
              top_score: 520,
              most_wickets: 'Naveen-Ul-Haq',
              wicket_count: 14,
            },
            {
              year: 2023,
              position: 3,
              top_scorer: 'Marcus Stoinis',
              top_score: 408,
              most_wickets: 'Ravi Bishnoi',
              wicket_count: 16,
            },
            {
              year: 2022,
              position: 4,
              top_scorer: 'K L Rahul',
              top_score: 616,
              most_wickets: 'Avesh Khan',
              wicket_count: 18,
            },
          ],
        },
        {
          team_name: 'Mumbai Indians',
          seasons: [
            {
              year: 2024,
              position: 10,
              top_scorer: 'Rohit Sharma',
              top_score: 417,
              most_wickets: 'Jasprit Bumrah',
              wicket_count: 20,
            },
            {
              year: 2023,
              position: 4,
              top_scorer: 'Suryakumar Yadav',
              top_score: 605,
              most_wickets: 'Piyush Chawla',
              wicket_count: 22,
            },
            {
              year: 2022,
              position: 10,
              top_scorer: 'Ishan Kishan',
              top_score: 418,
              most_wickets: 'Jasprit Bumrah',
              wicket_count: 15,
            },
            {
              year: 2021,
              position: 5,
              top_scorer: 'Rohit Sharma',
              top_score: 381,
              most_wickets: 'Jasprit Bumrah',
              wicket_count: 21,
            },
            {
              year: 2020,
              position: 1,
              top_scorer: 'Ishan Kishan',
              top_score: 516,
              most_wickets: 'Jasprit Bumrah',
              wicket_count: 27,
            },
            {
              year: 2019,
              position: 1,
              top_scorer: 'Quinton de Kock',
              top_score: 529,
              most_wickets: 'Jasprit Bumrah',
              wicket_count: 19,
            },
            {
              year: 2018,
              position: 5,
              top_scorer: 'Suryakumar Yadav',
              top_score: 512,
              most_wickets: 'Hardik Pandya',
              wicket_count: 18,
            },
            {
              year: 2017,
              position: 1,
              top_scorer: 'Parthiv Patel',
              top_score: 395,
              most_wickets: 'Jasprit Bumrah',
              wicket_count: 20,
            },
            {
              year: 2016,
              position: 5,
              top_scorer: 'Rohit Sharma',
              top_score: 489,
              most_wickets: 'Mitchell McClenaghan',
              wicket_count: 17,
            },
            {
              year: 2015,
              position: 1,
              top_scorer: 'Lendl Simmons',
              top_score: 540,
              most_wickets: 'Lasith Malinga',
              wicket_count: 24,
            },
            {
              year: 2014,
              position: 4,
              top_scorer: 'Lendl Simmons',
              top_score: 394,
              most_wickets: 'Lasith Malinga',
              wicket_count: 16,
            },
            {
              year: 2013,
              position: 1,
              top_scorer: 'Rohit Sharma',
              top_score: 538,
              most_wickets: 'Harbhajan Singh',
              wicket_count: 24,
            },
            {
              year: 2012,
              position: 4,
              top_scorer: 'Rohit Sharma',
              top_score: 433,
              most_wickets: 'Lasith Malinga',
              wicket_count: 22,
            },
            {
              year: 2011,
              position: 3,
              top_scorer: 'Sachin Tendulkar',
              top_score: 553,
              most_wickets: 'Lasith Malinga',
              wicket_count: 28,
            },
            {
              year: 2010,
              position: 2,
              top_scorer: 'Sachin Tendulkar',
              top_score: 618,
              most_wickets: 'Harbhajan Singh',
              wicket_count: 17,
            },
            {
              year: 2009,
              position: 7,
              top_scorer: 'JP Duminy',
              top_score: 372,
              most_wickets: 'Lasith Malinga',
              wicket_count: 18,
            },
            {
              year: 2008,
              position: 5,
              top_scorer: 'Sanath Jayasuriya',
              top_score: 518,
              most_wickets: 'Ashish Nehra',
              wicket_count: 12,
            },
          ],
        },
        {
          team_name: 'Punjab Kings',
          seasons: [
            {
              year: 2024,
              position: 9,
              top_scorer: 'Shashank Singh',
              top_score: 354,
              most_wickets: 'Harshal Patel',
              wicket_count: 24,
            },
            {
              year: 2023,
              position: 8,
              top_scorer: 'Shikhar Dhawan',
              top_score: 373,
              most_wickets: 'Arshdeep Singh',
              wicket_count: 17,
            },
            {
              year: 2022,
              position: 6,
              top_scorer: 'Shikhar Dhawan',
              top_score: 460,
              most_wickets: 'Kagiso Rabada',
              wicket_count: 23,
            },
            {
              year: 2021,
              position: 6,
              top_scorer: 'KL Rahul',
              top_score: 626,
              most_wickets: 'Mohammad Shami',
              wicket_count: 19,
            },
            {
              year: 2020,
              position: 6,
              top_scorer: 'KL Rahul',
              top_score: 670,
              most_wickets: 'Mohammad Shami',
              wicket_count: 20,
            },
            {
              year: 2019,
              position: 6,
              top_scorer: 'KL Rahul',
              top_score: 593,
              most_wickets: 'Mohammad Shami',
              wicket_count: 19,
            },
            {
              year: 2018,
              position: 7,
              top_scorer: 'KL Rahul',
              top_score: 659,
              most_wickets: 'Andrew Tye',
              wicket_count: 24,
            },
            {
              year: 2017,
              position: 5,
              top_scorer: 'Hashim Amla',
              top_score: 420,
              most_wickets: 'Sandeep Sharma',
              wicket_count: 17,
            },
            {
              year: 2016,
              position: 8,
              top_scorer: 'Murali Vijay',
              top_score: 453,
              most_wickets: 'Sandeep Sharma',
              wicket_count: 15,
            },
            {
              year: 2015,
              position: 8,
              top_scorer: 'David Miller',
              top_score: 357,
              most_wickets: 'Anureet Singh',
              wicket_count: 15,
            },
            {
              year: 2014,
              position: 2,
              top_scorer: 'Glenn Maxwell',
              top_score: 552,
              most_wickets: 'Sandeep Sharma',
              wicket_count: 18,
            },
            {
              year: 2013,
              position: 6,
              top_scorer: 'David Miller',
              top_score: 418,
              most_wickets: 'Parvinder Awana',
              wicket_count: 15,
            },
            {
              year: 2012,
              position: 6,
              top_scorer: 'Mandeep Singh',
              top_score: 432,
              most_wickets: 'Parvinder Awana',
              wicket_count: 17,
            },
            {
              year: 2011,
              position: 5,
              top_scorer: 'Shaun Marsh',
              top_score: 504,
              most_wickets: 'Piyush Chawla',
              wicket_count: 16,
            },
            {
              year: 2010,
              position: 8,
              top_scorer: 'Mahela Jayawardene',
              top_score: 439,
              most_wickets: 'Irfan Pathan',
              wicket_count: 15,
            },
            {
              year: 2009,
              position: 5,
              top_scorer: 'Yuvraj Singh',
              top_score: 340,
              most_wickets: 'Irfan Pathan',
              wicket_count: 17,
            },
            {
              year: 2008,
              position: 3,
              top_scorer: 'Shaun Marsh',
              top_score: 616,
              most_wickets: 'Shanthakumaran Sreesanth',
              wicket_count: 19,
            },
          ],
        },

        {
          team_name: 'Rajasthan Royals',
          seasons: [
            {
              year: 2024,
              position: 3,
              top_scorer: 'Riyan Parag',
              top_score: 573,
              most_wickets: 'Avesh Khan',
              wicket_count: 19,
            },
            {
              year: 2023,
              position: 5,
              top_scorer: 'Yashasvi Jaiswal',
              top_score: 625,
              most_wickets: 'Yuzvendra Chahal',
              wicket_count: 21,
            },
            {
              year: 2022,
              position: 2,
              top_scorer: 'Jos Buttler',
              top_score: 863,
              most_wickets: 'Yuzvendra Chahal',
              wicket_count: 27,
            },
            {
              year: 2021,
              position: 7,
              top_scorer: 'Sanju Samson',
              top_score: 484,
              most_wickets: 'Chris Morris',
              wicket_count: 15,
            },
            {
              year: 2020,
              position: 8,
              top_scorer: 'Sanju Samson',
              top_score: 375,
              most_wickets: 'Jofra Archer',
              wicket_count: 20,
            },
            {
              year: 2019,
              position: 7,
              top_scorer: 'Ajinkya Rahane',
              top_score: 393,
              most_wickets: 'Shreyas Gopal',
              wicket_count: 20,
            },
            {
              year: 2018,
              position: 4,
              top_scorer: 'Jos Buttler',
              top_score: 548,
              most_wickets: 'Jofra Archer',
              wicket_count: 15,
            },
            {
              year: 2015,
              position: 4,
              top_scorer: 'Ajinkya Rahane',
              top_score: 540,
              most_wickets: 'Chris Morris',
              wicket_count: 13,
            },
            {
              year: 2014,
              position: 5,
              top_scorer: 'Ajinkya Rahane',
              top_score: 339,
              most_wickets: 'Pravin Tambe',
              wicket_count: 15,
            },
            {
              year: 2013,
              position: 3,
              top_scorer: 'Shane Watson',
              top_score: 543,
              most_wickets: 'James Faulkner',
              wicket_count: 28,
            },
            {
              year: 2012,
              position: 7,
              top_scorer: 'Ajinkya Rahane',
              top_score: 560,
              most_wickets: 'Siddharth Trivedi',
              wicket_count: 13,
            },
            {
              year: 2011,
              position: 6,
              top_scorer: 'Rahul Dravid',
              top_score: 343,
              most_wickets: 'Shane Warne',
              wicket_count: 13,
            },
            {
              year: 2010,
              position: 7,
              top_scorer: 'Naman Ojha',
              top_score: 377,
              most_wickets: 'Siddharth Trivedi',
              wicket_count: 11,
            },
            {
              year: 2009,
              position: 6,
              top_scorer: 'Ravindra Jadeja',
              top_score: 295,
              most_wickets: 'Munaf Patel',
              wicket_count: 16,
            },
            {
              year: 2008,
              position: 1,
              top_scorer: 'Shane Watson',
              top_score: 472,
              most_wickets: 'Sohail Tanvir',
              wicket_count: 22,
            },
          ],
        },
        {
          team_name: 'Royal Challengers Bangalore',
          seasons: [
            {
              year: 2024,
              position: 4,
              top_scorer: 'Virat Kohli',
              top_score: 741,
              most_wickets: 'Yash Dayal',
              wicket_count: 15,
            },
            {
              year: 2023,
              position: 6,
              top_scorer: 'Faf Du Plessis',
              top_score: 730,
              most_wickets: 'Mohammed Siraj',
              wicket_count: 19,
            },
            {
              year: 2022,
              position: 3,
              top_scorer: 'Faf Du Plessis',
              top_score: 468,
              most_wickets: 'Wanindu Hasaranga',
              wicket_count: 26,
            },
            {
              year: 2021,
              position: 4,
              top_scorer: 'Glenn Maxwell',
              top_score: 513,
              most_wickets: 'Harshal Patel',
              wicket_count: 32,
            },
            {
              year: 2020,
              position: 4,
              top_scorer: 'Devdutt Padikkal',
              top_score: 473,
              most_wickets: 'Yuzvendra Chahal',
              wicket_count: 21,
            },
            {
              year: 2019,
              position: 8,
              top_scorer: 'Virat Kohli',
              top_score: 464,
              most_wickets: 'Yuzvendra Chahal',
              wicket_count: 18,
            },
            {
              year: 2018,
              position: 6,
              top_scorer: 'Virat Kohli',
              top_score: 530,
              most_wickets: 'Umesh Yadav',
              wicket_count: 20,
            },
            {
              year: 2017,
              position: 8,
              top_scorer: 'Virat Kohli',
              top_score: 308,
              most_wickets: 'Pawan Negi',
              wicket_count: 16,
            },
            {
              year: 2016,
              position: 2,
              top_scorer: 'Virat Kohli',
              top_score: 973,
              most_wickets: 'Yuzvendra Chahal',
              wicket_count: 21,
            },
            {
              year: 2015,
              position: 3,
              top_scorer: 'AB de Villiers',
              top_score: 513,
              most_wickets: 'Yuzvendra Chahal',
              wicket_count: 23,
            },
            {
              year: 2014,
              position: 7,
              top_scorer: 'AB de Villiers',
              top_score: 395,
              most_wickets: 'Varun Aaron',
              wicket_count: 16,
            },
            {
              year: 2013,
              position: 5,
              top_scorer: 'Chris Gayle',
              top_score: 708,
              most_wickets: 'Vinay Kumar',
              wicket_count: 23,
            },
            {
              year: 2012,
              position: 5,
              top_scorer: 'Chris Gayle',
              top_score: 733,
              most_wickets: 'Vinay Kumar',
              wicket_count: 19,
            },
            {
              year: 2011,
              position: 2,
              top_scorer: 'Chris Gayle',
              top_score: 608,
              most_wickets: 'Sreenath Aravind',
              wicket_count: 21,
            },
            {
              year: 2010,
              position: 3,
              top_scorer: 'Jacques Kallis',
              top_score: 572,
              most_wickets: 'Anil Kumble',
              wicket_count: 17,
            },
            {
              year: 2009,
              position: 2,
              top_scorer: 'Jacques Kallis',
              top_score: 361,
              most_wickets: 'Anil Kumble',
              wicket_count: 21,
            },
            {
              year: 2008,
              position: 7,
              top_scorer: 'Rahul Dravid',
              top_score: 371,
              most_wickets: 'Zaheer Khan',
              wicket_count: 13,
            },
          ],
        },
        {
          team_name: 'Sunrisers Hyderabad',
          seasons: [
            {
              year: 2024,
              position: 2,
              top_scorer: 'Travis Head',
              top_score: 567,
              most_wickets: 'T Natarajan',
              wicket_count: 19,
            },
            {
              year: 2023,
              position: 10,
              top_scorer: 'Heinrich Klaasen',
              top_score: 448,
              most_wickets: 'Bhuvneshwar Kumar',
              wicket_count: 16,
            },
            {
              year: 2022,
              position: 8,
              top_scorer: 'Abhishek Sharma',
              top_score: 426,
              most_wickets: 'Umran Malik',
              wicket_count: 22,
            },
            {
              year: 2021,
              position: 8,
              top_scorer: 'Manish Pandey',
              top_score: 292,
              most_wickets: 'Rashid Khan',
              wicket_count: 18,
            },
            {
              year: 2020,
              position: 3,
              top_scorer: 'David Warner',
              top_score: 548,
              most_wickets: 'Rashid Khan',
              wicket_count: 20,
            },
            {
              year: 2019,
              position: 4,
              top_scorer: 'David Warner',
              top_score: 692,
              most_wickets: 'Khaleel Ahmed',
              wicket_count: 19,
            },
            {
              year: 2018,
              position: 2,
              top_scorer: 'Kane Williamson',
              top_score: 735,
              most_wickets: 'Siddarth Kaul',
              wicket_count: 21,
            },
            {
              year: 2017,
              position: 4,
              top_scorer: 'David Warner',
              top_score: 641,
              most_wickets: 'Bhuvneshwar Kumar',
              wicket_count: 26,
            },
            {
              year: 2016,
              position: 1,
              top_scorer: 'David Warner',
              top_score: 848,
              most_wickets: 'Bhuvneshwar Kumar',
              wicket_count: 23,
            },
            {
              year: 2015,
              position: 6,
              top_scorer: 'David Warner',
              top_score: 562,
              most_wickets: 'Bhuvneshwar Kumar',
              wicket_count: 18,
            },
            {
              year: 2014,
              position: 6,
              top_scorer: 'David Warner',
              top_score: 528,
              most_wickets: 'Bhuvneshwar Kumar',
              wicket_count: 20,
            },
            {
              year: 2013,
              position: 4,
              top_scorer: 'Shikhar Dhawan',
              top_score: 311,
              most_wickets: 'Amit Mishra',
              wicket_count: 21,
            },
          ],
        },
      ],
    },
];

export const futureMatches = [    
    {
    "match_no": 33,
    "date": "April 17, 2025",
    "fixture": "Mumbai Indians vs Sunrisers Hyderabad",
    "stadium": "Wankhede Stadium, Mumbai",
    "time": "7:30 PM"
  },
  {
    "match_no": 34,
    "date": "April 18, 2025",
    "fixture": "Royal Challengers Bengaluru vs Punjab Kings",
    "stadium": "M. Chinnaswamy Stadium, Bengaluru",
    "time": "7:30 PM"
  },
  {
    "match_no": 35,
    "date": "April 19, 2025",
    "fixture": "Chennai Super Kings vs Rajasthan Royals",
    "stadium": "M. A. Chidambaram Stadium, Chennai",
    "time": "7:30 PM"
  },
  {
    "match_no": 36,
    "date": "April 20, 2025",
    "fixture": "Sunrisers Hyderabad vs Kolkata Knight Riders",
    "stadium": "Rajiv Gandhi International Stadium, Hyderabad",
    "time": "7:30 PM"
  },
  {
    "match_no": 37,
    "date": "April 21, 2025",
    "fixture": "Mumbai Indians vs Chennai Super Kings",
    "stadium": "Wankhede Stadium, Mumbai",
    "time": "7:30 PM"
  },
  {
    "match_no": 38,
    "date": "April 22, 2025",
    "fixture": "Kolkata Knight Riders vs Gujarat Titans",
    "stadium": "Eden Gardens, Kolkata",
    "time": "7:30 PM"
  },
  {
    "match_no": 39,
    "date": "April 23, 2025",
    "fixture": "Royal Challengers Bengaluru vs Lucknow Super Giants",
    "stadium": "M. Chinnaswamy Stadium, Bengaluru",
    "time": "7:30 PM"
  },{
    "match_no": 40,
    "date": "April 22, 2025",
    "fixture": "Lucknow Super Giants vs Delhi Capitals",
    "stadium": "BRSABV Ekana Cricket Stadium, Lucknow",
    "time": "7:30 PM"
  },
  {
    "match_no": 41,
    "date": "April 23, 2025",
    "fixture": "Sunrisers Hyderabad vs Mumbai Indians",
    "stadium": "Rajiv Gandhi International Stadium, Hyderabad",
    "time": "7:30 PM"
  },
  {
    "match_no": 42,
    "date": "April 24, 2025",
    "fixture": "Royal Challengers Bengaluru vs Rajasthan Royals",
    "stadium": "M. Chinnaswamy Stadium, Bengaluru",
    "time": "7:30 PM"
  },
  {
    "match_no": 43,
    "date": "April 25, 2025",
    "fixture": "Chennai Super Kings vs Sunrisers Hyderabad",
    "stadium": "M. A. Chidambaram Stadium, Chennai",
    "time": "7:30 PM"
  },
  {
    "match_no": 44,
    "date": "April 26, 2025",
    "fixture": "Kolkata Knight Riders vs Punjab Kings",
    "stadium": "Eden Gardens, Kolkata",
    "time": "7:30 PM"
  },
  {
    "match_no": 45,
    "date": "April 27, 2025",
    "fixture": "Mumbai Indians vs Lucknow Super Giants",
    "stadium": "Wankhede Stadium, Mumbai",
    "time": "3:30 PM"
  },
  {
    "match_no": 46,
    "date": "April 27, 2025",
    "fixture": "Delhi Capitals vs Royal Challengers Bengaluru",
    "stadium": "Arun Jaitley Stadium, Delhi",
    "time": "7:30 PM"
  },
  {
    "match_no": 47,
    "date": "April 28, 2025",
    "fixture": "Rajasthan Royals vs Gujarat Titans",
    "stadium": "Sawai Mansingh Stadium, Jaipur",
    "time": "7:30 PM"
  },
  {
    "match_no": 48,
    "date": "April 29, 2025",
    "fixture": "Delhi Capitals vs Kolkata Knight Riders",
    "stadium": "Arun Jaitley Stadium, Delhi",
    "time": "7:30 PM"
  },
  {
    "match_no": 49,
    "date": "April 30, 2025",
    "fixture": "Chennai Super Kings vs Punjab Kings",
    "stadium": "M. A. Chidambaram Stadium, Chennai",
    "time": "7:30 PM"
  },
  {
    "match_no": 50,
    "date": "May 1, 2025",
    "fixture": "Rajasthan Royals vs Mumbai Indians",
    "stadium": "Sawai Mansingh Stadium, Jaipur",
    "time": "7:30 PM"
  },
  {
    "match_no": 51,
    "date": "May 2, 2025",
    "fixture": "Gujarat Titans vs Sunrisers Hyderabad",
    "stadium": "Narendra Modi Stadium, Ahmedabad",
    "time": "7:30 PM"
  },
  {
    "match_no": 52,
    "date": "May 3, 2025",
    "fixture": "Royal Challengers Bengaluru vs Chennai Super Kings",
    "stadium": "M. Chinnaswamy Stadium, Bengaluru",
    "time": "7:30 PM"
  },
  {
    "match_no": 53,
    "date": "May 4, 2025",
    "fixture": "Kolkata Knight Riders vs Rajasthan Royals",
    "stadium": "Eden Gardens, Kolkata",
    "time": "3:30 PM"
  },
  {
    "match_no": 54,
    "date": "May 4, 2025",
    "fixture": "Punjab Kings vs Lucknow Super Giants",
    "stadium": "Dharamsala Stadium, Dharamsala",
    "time": "7:30 PM"
  },
  {
    "match_no": 55,
    "date": "May 5, 2025",
    "fixture": "Sunrisers Hyderabad vs Delhi Capitals",
    "stadium": "Rajiv Gandhi International Stadium, Hyderabad",
    "time": "7:30 PM"
  },
  {
    "match_no": 56,
    "date": "May 6, 2025",
    "fixture": "Mumbai Indians vs Gujarat Titans",
    "stadium": "Wankhede Stadium, Mumbai",
    "time": "7:30 PM"
  },
  {
    "match_no": 57,
    "date": "May 7, 2025",
    "fixture": "Kolkata Knight Riders vs Chennai Super Kings",
    "stadium": "Eden Gardens, Kolkata",
    "time": "7:30 PM"
  },
  {
    "match_no": 58,
    "date": "May 8, 2025",
    "fixture": "Punjab Kings vs Delhi Capitals",
    "stadium": "Dharamsala Stadium, Dharamsala",
    "time": "7:30 PM"
  },
  {
    "match_no": 59,
    "date": "May 9, 2025",
    "fixture": "Lucknow Super Giants vs Royal Challengers Bengaluru",
    "stadium": "BRSABV Ekana Cricket Stadium, Lucknow",
    "time": "7:30 PM"
  },
  {
    "match_no": 60,
    "date": "May 10, 2025",
    "fixture": "Sunrisers Hyderabad vs Kolkata Knight Riders",
    "stadium": "Rajiv Gandhi International Stadium, Hyderabad",
    "time": "7:30 PM"
  },
  {
    "match_no": 61,
    "date": "May 11, 2025",
    "fixture": "Punjab Kings vs Mumbai Indians",
    "stadium": "Dharamsala Stadium, Dharamsala",
    "time": "3:30 PM"
  },
  {
    "match_no": 62,
    "date": "May 11, 2025",
    "fixture": "Delhi Capitals vs Gujarat Titans",
    "stadium": "Arun Jaitley Stadium, Delhi",
    "time": "7:30 PM"
  },
  {
    "match_no": 63,
    "date": "May 12, 2025",
    "fixture": "Chennai Super Kings vs Rajasthan Royals",
    "stadium": "M. A. Chidambaram Stadium, Chennai",
    "time": "7:30 PM"
  },
  {
    "match_no": 64,
    "date": "May 13, 2025",
    "fixture": "Mumbai Indians vs Delhi Capitals",
    "stadium": "Wankhede Stadium, Mumbai",
    "time": "7:30 PM"
  },
  {
    "match_no": 65,
    "date": "May 14, 2025",
    "fixture": "Sunrisers Hyderabad vs Royal Challengers Bengaluru",
    "stadium": "Rajiv Gandhi International Stadium, Hyderabad",
    "time": "7:30 PM"
  },
  {
    "match_no": 66,
    "date": "May 15, 2025",
    "fixture": "Kolkata Knight Riders vs Lucknow Super Giants",
    "stadium": "Eden Gardens, Kolkata",
    "time": "7:30 PM"
  },
  {
    "match_no": 67,
    "date": "May 16, 2025",
    "fixture": "Gujarat Titans vs Punjab Kings",
    "stadium": "Narendra Modi Stadium, Ahmedabad",
    "time": "7:30 PM"
  },
  {
    "match_no": 68,
    "date": "May 17, 2025",
    "fixture": "Royal Challengers Bengaluru vs Sunrisers Hyderabad",
    "stadium": "M. Chinnaswamy Stadium, Bengaluru",
    "time": "7:30 PM"
  },
  {
    "match_no": 69,
    "date": "May 18, 2025",
    "fixture": "Rajasthan Royals vs Lucknow Super Giants",
    "stadium": "Sawai Mansingh Stadium, Jaipur",
    "time": "3:30 PM"
  },
  {
    "match_no": 70,
    "date": "May 18, 2025",
    "fixture": "Kolkata Knight Riders vs Royal Challengers Bengaluru",
    "stadium": "Eden Gardens, Kolkata",
    "time": "7:30 PM"
  },
  {
    "match_no": 71,
    "date": "May 19, 2025",
    "fixture": "Delhi Capitals vs Gujarat Titans",
    "stadium": "Arun Jaitley Stadium, Delhi",
    "time": "7:30 PM"
  },
  {
    "match_no": 72,
    "date": "May 20, 2025",
    "fixture": "Mumbai Indians vs Punjab Kings",
    "stadium": "Wankhede Stadium, Mumbai",
    "time": "7:30 PM"
  },
  {
    "match_no": 73,
    "date": "May 21, 2025",
    "fixture": "Chennai Super Kings vs Sunrisers Hyderabad",
    "stadium": "M. A. Chidambaram Stadium, Chennai",
    "time": "7:30 PM"
  },
  {
    "match_no": 74,
    "date": "May 22, 2025",
    "fixture": "Rajasthan Royals vs Kolkata Knight Riders",
    "stadium": "Sawai Mansingh Stadium, Jaipur",
    "time": "7:30 PM"
  }
]

export const matchesPlayed = [
    {
      "match_no": 19,
      "date": "April 6, 2025",
      "stadium": "Rajiv Gandhi International Stadium, Hyderabad",
      "time": "7:30 PM IST",
      "team1": "Gujarat Titans",
      "team2": "Sunrisers Hyderabad",
      "team1_score": "152/8",
      "team1_overs": "20.0",
      "team2_score": "153/3",
      "team2_overs": "16.4",
      "result": "Gujarat Titans won by 7 wickets"
    },
    {
      "match_no": 18,
      "date": "April 5, 2025",
      "stadium": "New PCA Stadium, New Chandigarh",
      "time": "7:30 PM IST",
      "team1": "Rajasthan Royals",
      "team2": "Punjab Kings",
      "team1_score": "155/9",
      "team1_overs": "20.0",
      "team2_score": "205/4",
      "team2_overs": "20.0",
      "result": "Rajasthan Royals won by 50 runs"
    },
    {
      "match_no": 17,
      "date": "April 5, 2025",
      "stadium": "MA Chidambaram Stadium, Chennai",
      "time": "3:30 PM IST",
      "team1": "Delhi Capitals",
      "team2": "Chennai Super Kings",
      "team1_score": "158/5",
      "team1_overs": "20.0",
      "team2_score": "183/6",
      "team2_overs": "20.0",
      "result": "Delhi Capitals won by 25 runs"
    },
    {
      "match_no": 16,
      "date": "April 4, 2025",
      "stadium": "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow",
      "time": "7:30 PM IST",
      "team1": "Lucknow Super Giants",
      "team2": "Mumbai Indians",
      "team1_score": "203/8",
      "team1_overs": "20.0",
      "team2_score": "191/5",
      "team2_overs": "20.0",
      "result": "Lucknow Super Giants won by 12 runs"
    },
    {
      "match_no": 15,
      "date": "April 3, 2025",
      "stadium": "Eden Gardens, Kolkata",
      "time": "7:30 PM IST",
      "team1": "Kolkata Knight Riders",
      "team2": "Sunrisers Hyderabad",
      "team1_score": "200/6",
      "team1_overs": "20.0",
      "team2_score": "120",
      "team2_overs": "16.4",
      "result": "Kolkata Knight Riders won by 80 runs"
    },
    {
      "match_no": 14,
      "date": "April 2, 2025",
      "stadium": "M Chinnaswamy Stadium, Bengaluru",
      "time": "7:30 PM IST",
      "team1": "Gujarat Titans",
      "team2": "Royal Challengers Bengaluru",
      "team1_score": "169/8",
      "team1_overs": "20.0",
      "team2_score": "170/2",
      "team2_overs": "17.5",
      "result": "Gujarat Titans won by 8 wickets"
    },
    {
      "match_no": 13,
      "date": "April 1, 2025",
      "stadium": "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow",
      "time": "7:30 PM IST",
      "team1": "Punjab Kings",
      "team2": "Lucknow Super Giants",
      "team1_score": "177/2",
      "team1_overs": "16.2",
      "team2_score": "171/7",
      "team2_overs": "20.0",
      "result": "Punjab Kings won by 8 wickets"
    },
    {
      "match_no": 12,
      "date": "March 31, 2025",
      "stadium": "Wankhede Stadium, Mumbai",
      "time": "7:30 PM IST",
      "team1": "Mumbai Indians",
      "team2": "Kolkata Knight Riders",
      "team1_score": "121/2",
      "team1_overs": "12.5",
      "team2_score": "116",
      "team2_overs": "16.2",
      "result": "Mumbai Indians won by 8 wickets"
    },
    {
      "match_no": 11,
      "date": "March 30, 2025",
      "stadium": "ACA Stadium, Guwahati",
      "time": "7:30 PM IST",
      "team1": "Rajasthan Royals",
      "team2": "Chennai Super Kings",
      "team1_score": "182/9",
      "team1_overs": "20.0",
      "team2_score": "176/6",
      "team2_overs": "20.0",
      "result": "Rajasthan Royals won by 6 runs"
    },
    {
      "match_no": 10,
      "date": "March 30, 2025",
      "stadium": "Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam",
      "time": "3:30 PM IST",
      "team1": "Delhi Capitals",
      "team2": "Sunrisers Hyderabad",
      "team1_score": "166/3",
      "team1_overs": "16.0",
      "team2_score": "163/4",
      "team2_overs": "20.0",
      "result": "Delhi Capitals won by 7 wickets"
    },
    {
      "match_no": 9,
      "date": "March 29, 2025",
      "stadium": "Narendra Modi Stadium, Ahmedabad",
      "time": "7:30 PM IST",
      "team1": "Gujarat Titans",
      "team2": "Mumbai Indians",
      "team1_score": "196/8",
      "team1_overs": "20.0",
      "team2_score": "160/6",
      "team2_overs": "20.0",
      "result": "Gujarat Titans won by 36 runs"
    },
    {
      "match_no": 8,
      "date": "March 28, 2025",
      "stadium": "MA Chidambaram Stadium, Chennai",
      "time": "7:30 PM IST",
      "team1": "Royal Challengers Bengaluru",
      "team2": "Chennai Super Kings",
      "team1_score": "196/7",
      "team1_overs": "20.0",
      "team2_score": "146/8",
      "team2_overs": "20.0",
      "result": "Royal Challengers Bengaluru won by 50 runs"
    },
    {
      "match_no": 7,
      "date": "March 27, 2025",
      "stadium": "Rajiv Gandhi International Stadium, Hyderabad",
      "time": "7:30 PM IST",
      "team1": "Lucknow Super Giants",
      "team2": "Sunrisers Hyderabad",
      "team1_score": "193/5",
      "team1_overs": "16.1",
      "team2_score": "190/9",
      "team2_overs": "20.0",
      "result": "Lucknow Super Giants won by 5 wickets"
    },
    {
      "match_no": 6,
      "date": "March 26, 2025",
      "stadium": "ACA Stadium, Guwahati",
      "time": "7:30 PM IST",
      "team1": "Kolkata Knight Riders",
      "team2": "Rajasthan Royals",
      "team1_score": "151/9",
      "team1_overs": "20.0",
      "team2_score": "153/2",
      "team2_overs": "17.3",
      "result": "Kolkata Knight Riders won by 8 wickets"
    },
    {
      "match_no": 5,
      "date": "March 25, 2025",
      "stadium": "Narendra Modi Stadium, Ahmedabad",
      "time": "7:30 PM IST",
      "team1": "Gujarat Titans",
      "team2": "Punjab Kings",
      "team1_score": "232/5",
      "team1_overs": "20.0",
      "team2_score": "243/5",
      "team2_overs": "20.0",
      "result": "Punjab Kings won by 11 runs"
    },
    {
      "match_no": 4,
      "date": "March 24, 2025",
      "stadium": "Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam",
      "time": "7:30 PM IST",
      "team1": "Delhi Capitals",
      "team2": "Lucknow Super Giants",
      "team1_score": "211/9",
      "team1_overs": "19.3",
      "team2_score": "209/8",
      "team2_overs": "20.0",
      "result": "Delhi Capitals won by 1 wicket"
    },
    {
      "match_no": 3,
      "date": "March 23, 2025",
      "stadium": "MA Chidambaram Stadium, Chennai",
      "time": "7:30 PM IST",
      "team1": "Chennai Super Kings",
      "team2": "Mumbai Indians",
      "team1_score": "158/6",
      "team1_overs": "19.1",
      "team2_score": "155/9",
      "team2_overs": "20.0",
      "result": "Chennai Super Kings won by 4 wickets"
    },
    {
      "match_no": 2,
      "date": "March 23, 2025",
      "stadium": "Rajiv Gandhi International Stadium, Hyderabad",
      "time": "3:30 PM IST",
      "team1": "Sunrisers Hyderabad",
      "team2": "Rajasthan Royals",
      "team1_score": "286/6",
      "team1_overs": "20.0",
      "team2_score": "242/6",
      "team2_overs": "20.0",
      "result": "Sunrisers Hyderabad won by 44 runs"
    },
    {
      "match_no": 1,
      "date": "March 22, 2025",
      "stadium": "Eden Gardens, Kolkata",
      "time": "7:30 PM IST",
      "team1": "Kolkata Knight Riders",
      "team2": "Royal Challengers Bengaluru",
      "team1_score": "174/8",
      "team1_overs": "20.0",
      "team2_score": "177/3",
      "team2_overs": "16.2",
      "result": "Royal Challengers Bengaluru won by 7 wickets"
    },
    {
      "match_no": 32,
      "date": "April 16, 2025",
      "stadium": "Arun Jaitley Stadium, Delhi",
      "time": "7:30 PM IST",
      "team1": "Delhi Capitals",
      "team2": "Rajasthan Royals",
      "team1_score": "188/5",
      "team1_overs": "20.0",
      "team2_score": "188/4",
      "team2_overs": "20.0",
      "super_over_team1_score": "13/0",
      "super_over_team2_score": "11/2",
      "result": "Delhi Capitals won by Super Over"
    },
    {
      "match_no": 31,
      "date": "April 15, 2025",
      "stadium": "New PCA Stadium, New Chandigarh",
      "time": "7:30 PM IST",
      "team1": "Punjab Kings",
      "team2": "Kolkata Knight Riders",
      "team1_score": "111",
      "team1_overs": "15.3",
      "team2_score": "95",
      "team2_overs": "15.1",
      "result": "Punjab Kings won by 16 runs"
    },
    {
      "match_no": 30,
      "date": "April 14, 2025",
      "stadium": "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow",
      "time": "7:30 PM IST",
      "team1": "Lucknow Super Giants",
      "team2": "Chennai Super Kings",
      "team1_score": "166/7",
      "team1_overs": "20.0",
      "team2_score": "168/5",
      "team2_overs": "19.3",
      "result": "Chennai Super Kings won by 5 wickets"
    },
    {
      "match_no": 29,
      "date": "April 13, 2025",
      "stadium": "Arun Jaitley Stadium, Delhi",
      "time": "7:30 PM IST",
      "team1": "Delhi Capitals",
      "team2": "Mumbai Indians",
      "team1_score": "193",
      "team1_overs": "19.0",
      "team2_score": "205/5",
      "team2_overs": "20.0",
      "result": "Mumbai Indians won by 12 runs"
    },
    {
      "match_no": 28,
      "date": "April 13, 2025",
      "stadium": "Sawai Mansingh Stadium, Jaipur",
      "time": "3:30 PM IST",
      "team1": "Rajasthan Royals",
      "team2": "Royal Challengers Bengaluru",
      "team1_score": "173/4",
      "team1_overs": "20.0",
      "team2_score": "175/1",
      "team2_overs": "17.3",
      "result": "Royal Challengers Bengaluru won by 9 wickets"
    },
    {
      "match_no": 27,
      "date": "April 12, 2025",
      "stadium": "Rajiv Gandhi International Stadium, Hyderabad",
      "time": "7:30 PM IST",
      "team1": "Sunrisers Hyderabad",
      "team2": "Punjab Kings",
      "team1_score": "247/2",
      "team1_overs": "18.3",
      "team2_score": "245/6",
      "team2_overs": "20.0",
      "result": "Sunrisers Hyderabad won by 8 wickets"
    },
    {
      "match_no": 26,
      "date": "April 12, 2025",
      "stadium": "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow",
      "time": "3:30 PM IST",
      "team1": "Lucknow Super Giants",
      "team2": "Gujarat Titans",
      "team1_score": "186/4",
      "team1_overs": "19.3",
      "team2_score": "180/6",
      "team2_overs": "20.0",
      "result": "Lucknow Super Giants won by 6 wickets"
    },
    {
      "match_no": 25,
      "date": "April 11, 2025",
      "stadium": "MA Chidambaram Stadium, Chennai",
      "time": "7:30 PM IST",
      "team1": "Chennai Super Kings",
      "team2": "Kolkata Knight Riders",
      "team1_score": "103/9",
      "team1_overs": "20.0",
      "team2_score": "107/2",
      "team2_overs": "10.1",
      "result": "Kolkata Knight Riders won by 8 wickets"
    },
    {
      "match_no": 24,
      "date": "April 10, 2025",
      "stadium": "M Chinnaswamy Stadium, Bengaluru",
      "time": "7:30 PM IST",
      "team1": "Royal Challengers Bengaluru",
      "team2": "Delhi Capitals",
      "team1_score": "163/7",
      "team1_overs": "20.0",
      "team2_score": "169/4",
      "team2_overs": "17.5",
      "result": "Delhi Capitals won by 6 wickets"
    },
    {
      "match_no": 23,
      "date": "April 9, 2025",
      "stadium": "Narendra Modi Stadium, Ahmedabad",
      "time": "7:30 PM IST",
      "team1": "Gujarat Titans",
      "team2": "Rajasthan Royals",
      "team1_score": "217/6",
      "team1_overs": "20.0",
      "team2_score": "159",
      "team2_overs": "19.2",
      "result": "Gujarat Titans won by 58 runs"
    },
    {
      "match_no": 22,
      "date": "April 8, 2025",
      "stadium": "New PCA Stadium, New Chandigarh",
      "time": "7:30 PM IST",
      "team1": "Punjab Kings",
      "team2": "Chennai Super Kings",
      "team1_score": "219/6",
      "team1_overs": "20.0",
      "team2_score": "201/5",
      "team2_overs": "20.0",
      "result": "Punjab Kings won by 18 runs"
    },
    {
      "match_no": 21,
      "date": "April 8, 2025",
      "stadium": "Eden Gardens, Kolkata",
      "time": "3:30 PM IST",
      "team1": "Kolkata Knight Riders",
      "team2": "Lucknow Super Giants",
      "team1_score": "234/7",
      "team1_overs": "20.0",
      "team2_score": "238/3",
      "team2_overs": "20.0",
      "result": "Lucknow Super Giants won by 4 runs"
    },
    {
      "match_no": 20,
      "date": "April 7, 2025",
      "stadium": "Wankhede Stadium, Mumbai",
      "time": "7:30 PM IST",
      "team1": "Mumbai Indians",
      "team2": "Royal Challengers Bengaluru",
      "team1_score": "209/9",
      "team1_overs": "20.0",
      "team2_score": "221/5",
      "team2_overs": "20.0",
      "result": "Royal Challengers Bengaluru won by 12 runs"
    }
  ]
export const videoInfo={
    "Latest Videos": [
      {
        "heading": "Super Over Stars",
        "date": "18 Apr, 2025",
        "views": "31.2k",
        "duration": "03:18 mins"
      },
      {
        "heading": "Credit to Starc for the Way He Bowled",
        "date": "18 Apr, 2025",
        "views": "56.4k",
        "duration": "05:15 mins"
      },
      {
        "heading": "Player of the Match...",
        "date": "17 Apr, 2025",
        "views": "26.7k",
        "duration": "08:12 mins"
      },
      {
        "heading": "Mitchell is Clear of His Plans...",
        "date": "16 Apr, 2025",
        "views": "23.4k",
        "duration": "06:24 mins"
      }
    ],
    "Magic Moments": [
      {
        "heading": "MSD Finishes Off in Style",
        "date": "15 Apr, 2025",
        "views": "88.1k",
        "duration": "02:45 mins"
      },
      {
        "heading": "One Handed Stunner by Rinku",
        "date": "14 Apr, 2025",
        "views": "42.3k",
        "duration": "01:30 mins"
      },
      {
        "heading": "Pollard Smashes 3 Sixes in a Row",
        "date": "13 Apr, 2025",
        "views": "38.9k",
        "duration": "02:22 mins"
      },
      {
        "heading": "Unbelievable Catch on the Boundary!",
        "date": "13 Apr, 2025",
        "views": "49.5k",
        "duration": "01:58 mins"
      }
    ],
    "Highlights": [
      {
        "heading": "CSK vs MI Match Highlights",
        "date": "17 Apr, 2025",
        "views": "112.3k",
        "duration": "09:20 mins"
      },
      {
        "heading": "RCB vs KKR Thriller Recap",
        "date": "16 Apr, 2025",
        "views": "97.6k",
        "duration": "08:50 mins"
      },
      {
        "heading": "RR's Stunning Run Chase",
        "date": "15 Apr, 2025",
        "views": "76.4k",
        "duration": "07:40 mins"
      },
      {
        "heading": "Punjab’s Powerplay ",
        "date": "14 Apr, 2025",
        "views": "63.2k",
        "duration": "06:18 mins"
      }
    ]
  }

  export const newsInfo ={
    "Latest News": [
      {
        "heading": "Rohit Sharma Discusses Team Strategy Ahead of Big Match",
        "date": "18 Apr, 2025"
      },
      {
        "heading": "Injury Update: Bumrah Likely to Miss Next Two Games",
        "date": "17 Apr, 2025"
      },
      {
        "heading": "Dravid Talks About India’s Bench Strength",
        "date": "16 Apr, 2025"
      },
      {
        "heading": "New Opening Pair Set to Debut Tomorrow",
        "date": "15 Apr, 2025"
      }
    ],
    "Match Reports": [
      {
        "heading": "Chennai Super Kings's Edge Past RCB in Last-Over Thriller",
        "date": "17 Apr, 2025"
      },
      {
        "heading": "MI Collapse Hands Win to Punjab",
        "date": "16 Apr, 2025"
      },
      {
        "heading": "KKR’s Spinners Dominate on a Turning Track",
        "date": "15 Apr, 2025"
      },
      {
        "heading": "Sunrisers Seal Comfortable Victory Over Royals",
        "date": "14 Apr, 2025"
      }
    ],
    "Announcements": [
      {
        "heading": "India Squad Announced for T20 World Cup 2025",
        "date": "18 Apr, 2025"
      },
      {
        "heading": "BCCI Releases Domestic Schedule for 2025-26",
        "date": "17 Apr, 2025"
      },
      {
        "heading": "New Jersey Unveiled for Team India",
        "date": "16 Apr, 2025"
      },
      {
        "heading": "Ticket Sales Open for Playoff Matches",
        "date": "15 Apr, 2025"
      }
    ]
  }